### ISSUE TITLE
[FEAT] 프로젝트 초기세팅

### ISSUE THREAD

**Issue by amourxyoung** [GOSOPT-CDS-TEAM-APP5/Lotte-Cinema-AOS#1]
## Todo
- [X] MVVM 패키지 구조에 더미 파일 추가
- [x] textAppearance / color 추가
- [X] 라이브러리 dependency 추가
- [X] gitIgnore 설정
- [X] gradle version 설정
