### ISSUE TITLE
[FEAT] 영화 선택 뷰 서버통신 구현

### ISSUE THREAD

**Issue by amourxyoung** [GOSOPT-CDS-TEAM-APP5/Lotte-Cinema-AOS#13]
## Todo
- [x] 영화관 지역 리스트 api 연결
- [x] 지역에 해당하는 영화관 목록 api 연결
- [x] 지점 선택시 그에 해당하는 chip 뜨게끔 구현
- [x] 영화 타임테이블 api 연결
