### ISSUE TITLE
[FEAT] 영화관 선택 뷰 구현

### ISSUE THREAD

**Issue by amourxyoung** [GOSOPT-CDS-TEAM-APP5/Lotte-Cinema-AOS#2]
## Todo
- [x] 상단 영화 정보 뷰 xml 구현
- [x] item click event 추가
- [x] 지역 선택 recyclerView 구현
- [x] 지점 선택 recyclerView 구현
