### ISSUE TITLE
[FEAT] 홈 화면 뷰 구현

### ISSUE THREAD

**Issue by ss99x2002** [GOSOPT-CDS-TEAM-APP5/Lotte-Cinema-AOS#3]
## Todo
- [x] 상단 ViewPager 구현 (dot indicator)
- [x] 무비 차트 RecyclerView (멀티뷰 타입)
- [x] bottom navigation custom
- [x] 이벤트 구현 (중첩 프래그먼트)
- [x] 무비 피드 구현 (RecyclerView)
- [x] 스페셜관 구현
- [x] 아래 배너 구현

**Comment by ss99x2002** [comment]
완료
