### ISSUE TITLE
[FEAT] 영화 선택 뷰 세부 ui 구현

### ISSUE THREAD

**Issue by amourxyoung** [GOSOPT-CDS-TEAM-APP5/Lotte-Cinema-AOS#7]
## Todo
- [x] 지역 선택 아이템 클릭시 지점 선택 리사이클러뷰가 나오도록 구현
- [x] 3개 지점 아이템 클릭시 버튼 색깔 변경
- [ ] 선택한 지점명이 chip 형태로 보이게끔 구현
