### ISSUE TITLE
[FEAT] 영화 시간 선택 뷰 구현

### ISSUE THREAD

**Issue by amourxyoung** [GOSOPT-CDS-TEAM-APP5/Lotte-Cinema-AOS#8]
## Todo
- [x] tool bar 구현
- [x] 상단 영화 정보 구현
- [x] 캘린더뷰 구현
- [x] 지점별 상세 영화 시간뷰 구현
